language: python
python:
- "3.8"
- "3.9"

# command to install dependencies
install:
- pip install .[dev]

# command to run tests
script:
- pytest
- coverage run -m --source=uavnoma pytest

# Push the results back to codecov
after_success:
  - codecov