language: python
python:
- "3.7"
- "3.8"
- "3.9"

# command to install dependencies 
install:
- pip install pip
- pip install setup.py
- pip install . pauavnoma

# command to run tests 
script:
- python tests/test_pauavnoma.py pytest